export const MSG = {
  PING: 'PING',
  // Worker
  START_FLOW: 'START_FLOW',
  GET_RECENT: 'GET_RECENT',
  GET_PREFS: 'GET_PREFS',
  SET_PREFS: 'SET_PREFS',
  MARK_STAGE_DONE: 'MARK_STAGE_DONE',
  SET_FLOW_STATUS: 'SET_FLOW_STATUS',
  // Content
  REQUEST_ROW_KEY: 'REQUEST_ROW_KEY',
  OPEN_PANEL: 'OPEN_PANEL',
  CLOSE_PANEL: 'CLOSE_PANEL',
  REFRESH_PANEL: 'REFRESH_PANEL'
};
